apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice-deployment
spec:
  #replicas: 2  # Numero totale di pod
  selector:
    matchLabels:
      microservice: products
  template:
    metadata:
      labels:
        microservice: products
        app: e-commerce
    spec:
      containers:
        - name: products-microservice-container
          imagePullPolicy: Never
          image: products-microservice-image
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
          ports:
            - containerPort: 443
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5