apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-microservice-deployment
spec:
  selector:
    matchLabels:
      microservice: authentication
  template:
    metadata:
      labels:
        microservice: authentication
        app: e-commerce
    spec:
      containers:
        - name: authentication-microservice-container
          imagePullPolicy: Never
          image: authentication-microservice-image
          ports:
            - containerPort: 443
          env:
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_SECRET_KEY
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

