apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_USERNAME: Y2hyaXN0aWFu    # "christian" in base64
  DB_PASSWORD: Y2hyaXN0aWFu    # "christian" in base64
